### ISSUE TITLE
What is the lowest version of supported browser?

### ISSUE THREAD

**Issue by Paper-Folding** [minditor/minditor#1]
What is the lowest version of supported browser?
As I dig through the doc, I found version requirements of browser is rather high, can you list lowest supported version of browsers?
![image](https://github.com/minditor/minditor/assets/49343539/ef106b06-e91e-4f5f-9e93-4c3a40e836d7)

**Comment by sskyy** [comment]
> What is the lowest version of supported browser? As I dig through the doc, I found version requirements of browser is rather high, can you list lowest supported version of browsers? ![image](https://private-user-images.githubusercontent.com/49343539/309154743-ef106b06-e91e-4f5f-9e93-4c3a40e836d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NDc3NjMsIm5iZiI6MTcwOTQ0NzQ2MywicGF0aCI6Ii80OTM0MzUzOS8zMDkxNTQ3NDMtZWYxMDZiMDYtZTkxZS00ZjVmLTllOTMtNGMzYTQwZTgzNmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA2MzEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZmY2ZmFhODI0M2ViYWYxMDAwM2IwMjgzYzliMmUzMDE1NDUyMGQwMTBiMzVkMjkyNTY3Y2ViNDc0N2U4YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.13MC1PeBpm5OSC7wiZA0LWVboqKQdMECMSp3Ri6zhfI)

I will do a complete test against all recent versions of major browsers soon.
