### ISSUE TITLE
Error with vite

### ISSUE THREAD

**Issue by abasse** [minditor/minditor#2]
When I try to run the code (after install with: npm install minditor) :

` import './style.css'

import {
  Code,
  Grid,
  Heading,
  InlineCode,
  Link,
  OLItem,
  Paragraph,
  Text,
  ULItem,
  InlineImageBlock
} from "minditor";

const rootElement = document.getElementById('root');
const types = {
  Paragraph,
  Text,
  Heading,
  OLItem,
  ULItem,
  InlineCode,
  Code,
  Link,
  Grid,
  Image: InlineImageBlock
}
const data = {
  name: 'MyDoc',
  children: [{
    type: 'Paragraph',
    content: [{ type: 'Text', value: 'This is my first document.' }]
  }]
}

const doc = new Document(rootElement, data, types)
doc.render() `

I receive follwing error:

Failed to resolve entry for package "minditor". The package may have incorrect main/module/exports specified in its package.json.

(latest vite verision)

**Comment by sskyy** [comment]
> When I try to run the code (after install with: npm install minditor) :
> 
> ` import './style.css'
> 
> import { Code, Grid, Heading, InlineCode, Link, OLItem, Paragraph, Text, ULItem, InlineImageBlock } from "minditor";
> 
> const rootElement = document.getElementById('root'); const types = { Paragraph, Text, Heading, OLItem, ULItem, InlineCode, Code, Link, Grid, Image: InlineImageBlock } const data = { name: 'MyDoc', children: [{ type: 'Paragraph', content: [{ type: 'Text', value: 'This is my first document.' }] }] }
> 
> const doc = new Document(rootElement, data, types) doc.render() `
> 
> I receive follwing error:
> 
> Failed to resolve entry for package "minditor". The package may have incorrect main/module/exports specified in its package.json.
> 
> (latest vite verision)

Fixed with version 1.0.9. Thanks for submit this issue!
